name: Build, Publish and Deploy to Production

on:
  release:
    types: [released]

env:
  IMAGE_TAG: ${{ github.event.release.tag_name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Build and push Docker image
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIT_USER: ${{ secrets.GIT_USER }}
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/tags/}
          docker build . --file Dockerfile --tag turistikrota/site:$IMAGE_TAG
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push turistikrota/site:$IMAGE_TAG

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Pull and run the Docker image on the server
        uses: appleboy/ssh-action@master
        env:
          DIR: ${{ secrets.DIR }} 
          APP_PORT: ${{ secrets.APP_PORT }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          envs: DIR,APP_PORT,IMAGE_TAG
          script: |
            docker service ls | grep -q site && docker service rm site || true
            cd $DIR
            docker pull turistikrota/site:$IMAGE_TAG
            docker service create --name site --env-file .env --publish $APP_PORT:3000 --hostname 0.0.0.0 turistikrota/site:$IMAGE_TAG
