name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
          DIR: ${{ secrets.DIR }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: DIR
          script: |
            cd $DIR
            git checkout main
            git pull origin main
            docker rm -f $(docker ps -f ancestor=turistikrota.com -q)
            docker build -t turistikrota.com .
            docker run -d -p 3000:3000 -t turistikrota.com
