name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
          DIR: ${{ secrets.DIR }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: DIR
          script: |
            cd $DIR
            git checkout main
            git pull origin main
            docker build -t turistikrota-site .
            docker service rm turistikrota-site
            docker service create --name turistikrota-site --publish 3000:3000 turistikrota-site
