name: Build, Publish and Deploy to RC

on:
  release:
    types: [prereleased]

env:
  IMAGE_TAG: ${{ github.event.release.tag_name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and publish docker
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/tags/}
          docker build . --file Dockerfile --tag turistikrota/site-rc:$IMAGE_TAG --platform darwin/amd64
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push turistikrota/site-rc:$IMAGE_TAG

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Pull and run the Docker image on the server
        uses: appleboy/ssh-action@master
        env:
          DIR: ${{ secrets.RC_DIR }} 
          RC_APP_PORT: ${{ secrets.RC_APP_PORT }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          envs: DIR,RC_APP_PORT,IMAGE_TAG
          script: |
            docker service ls | grep -q site-rc && docker service rm site-rc || true
            cd $DIR
            docker pull turistikrota/site-rc:$IMAGE_TAG
            docker service create --name site-rc --env-file .env --publish $RC_APP_PORT:3000 --hostname 0.0.0.0 turistikrota/site-rc:$IMAGE_TAG
